CREATE DATABASE eo_vipdb;
USE eo_vipdb;

-- Tables----------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `VIPs`
(
	`ID` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Username` VARCHAR(25) NOT NULL,
	`VIPLevel` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`Timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`SpawnInBase` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponPreset` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponMeleeSlot` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponPistolSlot` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponShotgunSlot` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponSubMachineSlot` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponAssaultSlot` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
	`WeaponRifleSlot` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
            
	CONSTRAINT pk_id PRIMARY KEY(`ID`)
);

SELECT * FROM `VIPs`;